### ISSUE TITLE
Request for Google Sheets

### ISSUE THREAD

**Issue by effofxprime** [slowli/bech32-buffer#91]
Hello sir!
I was wondering if it would be possible if I could use this tool in Google Sheet?

I am having to convert hex identifiers to their bech32 prefix to match validators properly within our chain.

Would it be possible to make it so I could use it in a format like:(example)
```
https://slowli.github.io/bech32-buffer/data/?tag=vdlvalcons&encoding=bech32&data=4C1438CDA672B766D7BA69A79DC462DD389875BE
```
and then be returned: 
```
vdlvalcons1fs2r3ndxw2mkd4a6dxnem3rzm5ufsad7058gmw
```

**Comment by slowli** [comment]
Hi! Terribly sorry for the delayed response. Unfortunately, this functionality does not possible with the hosting provider for `slowli.github.io` (i.e., [GitHub Pages](https://pages.github.com/)) since it only allows static contents. Since the purpose of the demo website is just to demo the package functionality, I don't think it would be reasonable to move it to a different hosting provider just for the purpose of providing this functionality.
